server {
    listen 80;
    server_name calebzaleski.com;
    root /usr/share/nginx/html;

    location = /home {
        try_files /index.html =404;
    }

    location = /bible {
        try_files /bible/bible.html =404;
    }

    location = /recipe_app {
        try_files /dropdown/recipe-app.html =404;
    }

    location = /webserver {
        try_files /dropdown/website.html =404;
    }

    location = /3d_printing {
        try_files /dropdown/3D_Printing.html =404;
    }

    location = /admin {
        try_files /dropdown/Admin.html =404;
    }
    location = /about {
            try_files /about.html =404;
        }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}